### ISSUE TITLE
Allow shrinking to a single symbol in fragment selector (low priority)

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#112]
It'd be nice to allow shrinking to a single symbol in the fragment selector, at least for symbols that aren't "parentheses-like".

* If you select `->` you only get the surrounding `(... -> ....)`, it cannot be shrunk further.
* If you select `=` or `e.` you again *only* get the surrounding expression; you can't shrink to 1 symbol.

Oddly, you can already get "just the symbol" when you click on "+" or "x." (infix functions). In fact, when you click on them, you by *default* get just the symbol, and have to expand. That behavior is okay, it just seems oddly inconsistent & I don't understand the rule it's using. (I'd love to understand why.)

I think this is low priority right now, but if [paste in the fragment selection bar](https://github.com/expln/metamath-lamp/issues/42) or [pretty mode](https://github.com/expln/metamath-lamp/issues/40) are added this ability to shrink to one symbol would become even more useful. And while neither of those are high priority for me (compared to undo/redo or full unification), they would be nice someday. So I thought I'd create this issue now :-).

**Comment by expln** [comment]
@david-a-wheeler I made changes to allow shrinking to a single symbol. This is available on dev. However, initial selection is not changed, it still will select a sequence of symbols in one case and only a single symbol in another case. The logic is as follows.

Mm-lamp tries to select what has meaning. Suppose we are clicking on the `CC` in `|- 1 e. CC`. Then only `CC` is selected because `CC` stands for the class of complex numbers, which may have meaning on its own and users may want to select only it. Mm-lamp understands this but looking at the corresponding syntax assertion. `CC` is placed instead of the `B` variable in the syntax assertion:

![image](https://github.com/expln/metamath-lamp/assets/47696142/91e25aec-2687-4b95-a635-d5bc9c4f0224)

When clicking on `e.` the entire expression gets selected because `e.` doesn't have meaning on its own so I think users will not want to select only this symbol. So mm-lamp expands selection by one level to have something meaningful selected rightaway. Mm-lamp understands this by seeing that `e.` is a constant in the syntax assertion:

![image](https://github.com/expln/metamath-lamp/assets/47696142/87d05dfb-5793-447e-9d0c-e1ae3fc83e7d)

With the `+` operator, mm-lamp uses the same approach of checking the syntax assertion. But the `+` symbol is placed instead of the `F` variable, so mm-lamp "thinks" it may have a meaning on its own and selects only it:

![image](https://github.com/expln/metamath-lamp/assets/47696142/8be2a0f8-6918-492c-b768-801905f7c371)

Previously it was not possible to shrink selection to a single symbol. But with the last update it is possible now.

**Comment by expln** [comment]
This is available in version 15 https://expln.github.io/lamp/v15/index.html

**Comment by david-a-wheeler** [comment]
That's great!

While the *syntax* rules may not allow a single symbol, there are definitely cases where you want to copy a symbol onto another. E.g., replacing `/\` with `\/`.
