### ISSUE TITLE
Add transitively skipped assertions option

### ISSUE THREAD

**Issue by CatsAreFluffy** [expln/metamath-lamp#152]
For example, if I was trying to prove a theorem without using ~ ax-rep, I would want to skip not just ax-rep, but all theorems using ax-rep.

**Comment by expln** [comment]
Ok, that makes sense. I will implement it.

**Comment by expln** [comment]
This is implemented on [dev](https://expln.github.io/lamp/dev/index.html).

Please read this [comment ](https://github.com/expln/metamath-lamp/issues/31#issuecomment-1682725469) to understand the new settings which allow to skip some assertion and all the theorems depending on it.

In order to skip ax-rep and all theorems using ax-rep, you may set the new settings as follows:

![image](https://github.com/expln/metamath-lamp/assets/47696142/2e4045ab-acd5-48d9-aafa-48ba5e6ab7b4)
