### ISSUE TITLE
Overflow for mmContext ?

### ISSUE THREAD

**Issue by billh0420** [expln/metamath-lamp#78]
If all the data is loaded for set.mm, it appears that the mmContext preCtx has the buckets for frames to reach the maximum size of 65536 (2^32).

Using the debugger, I got for all of set.mm the following:

1) preCtx frames size is 43657;
2) its buckets size is 65536.

If I only load set.mm before mulm1, I get the following:

1) preCtx frames size is 10815;
2) its buckets size is 16384.

**Comment by expln** [comment]
That's interesting. I never thought about this case. I will definitely analyze it more deep.

**Comment by david-a-wheeler** [comment]
I'm confused.
2^16 is 65536.
2^32 is 4 294 967 296.
Which is the max?

**Comment by billh0420** [comment]
I guess I meant 2^16 rather than 2^32.

I don't think I could find what the max rescript array size is. But when I was looking at the sizes of variables, I noticed that the buckets size was a high power of 2 (which looked suspicious since that would be unlikely). I'm not sure why an error was not raised when more items were being added (the error may have been ignored).

Or, it could not be a problem and I am misunderstanding something.

**Comment by billh0420** [comment]
Looking at it more closely, there may not be a problem. It looks like rescript is filling out its arrays to the highest power of 2 (or is buckets a dictionary).

Note that for the second example where only load set.mm before mulm1, the buckets size is 16384 = 2 ^ 14.

Sorry for the false alarm.

**Comment by expln** [comment]
Those buckets must be a part of a hash map. I briefly looked at the JS code generated by ReScript compiler and I didn't notice there any validation of possible integer overflow. However, as David noticed, 2^32 is 4 294 967 296 which is a pretty big number and not so easy to reach. I will not close this issue, because I want to artificially create a big number of assertions and check how it works in that case.

**Comment by david-a-wheeler** [comment]
Technically JavaScript doesn't have integers at all. JavaScript Numbers are Always 64-bit Floating Point. The [maximum *safe* integer value in JavaScript is the largest integer it can safely represent without inaccuracy; its value is Number.MAX_SAFE_INTEGER = (2^53)-1 = 9007199254740991 (about 9 quadrillion)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

However, on many systems integer calculations are faster, so it's helpful to hint to the JavaScript compiler that "this is really an integer" even though there's no way to notate that. A common trick is to append "|0" ("or with 0") to numbers. [The "|" is a bitwise operator](https://www.w3schools.com/js/js_bitwise.asp) that's built into JavaScript, so it's a backwards-compatible way to indicate that "this result is an integer". Officially a JavaScript interpreter will convert the value to a 32-bit signed integer, do the bitwise calculation, and then convert back to a 64-bit float. A smarter JavaScript interpreter can use this information to optimize things.

Rescript originally worked with OCaml and JavaScript. Now that Rescript is focused on JavaScript, there's debate on whether or not integers should stay limited to (2^31)-1:
https://forum.rescript-lang.org/t/is-int-still-limited-to-2147483648-2147483647/3455
JavaScript numbers *themselves* aren't limited to this size, but if you want to portably hint to it to use integers, then they *are* limited to this size.

**Comment by david-a-wheeler** [comment]
I think this question is resolved & we can close this. @billh0420 - do you agree?

**Comment by expln** [comment]
I want to do some experiments with big number of frames, so please don't close this issue, it is a reminder for me.

**Comment by expln** [comment]
I've experimented with increased number of assertions in set.mm. In order to increase number of assertions I modified addAssertion function in MM_context.res as shown at the end of this comment. Also, to see the real data, I modified actCtxUpdated function in MM_cmp_root.res.

When I increased number of assertions by 5:
* frames.size=216760, buckets.size=131072
* loading the context is slower
* the first unification is also slower
* however, consecutive unifications are fast enough (still slower, but not so much as the first one)
* after using Explorer for some amount of time I've got a JS error in the browser console which I could not understand (but it was not an out of memory)

When I increased number of assertions by 10:
* frames.size=433520, buckets.size=262144
* loading the context is much slower
* the first unification resulted in "Out of Memory" error.

These experiments confirmed that there is no any problem with number of buckets. Also, when size of set.mm increases by 2 or 3, I think, mm-lamp will still be usable. However, the strange error I saw in the browser console needs more attention. It may be not related to the increased amount of data.

My system configuration is:
Processor 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
RAM 16.0 GB
Windows 11
Google Chrome Version 114.0.5735.199 (Official Build) (64-bit)

Log real data to the console:
```
let actCtxUpdated = (srcs:array<mmCtxSrcDto>, newCtx:mmContext) => {
    Js.Console.log2(`newCtx`, newCtx)
    actCloseFrmTabs()
    setState(updatePreCtxData(_,~ctx=(srcs,newCtx), ()))
}
```

Increase number of assertions by executing a part of the code in a loop:
```
let addAssertion = ( ctx:mmContext, ~isAxiom:bool, ~label:string, ~exprStr:array<string>, ~proof:option<proof> ):unit => {
    let frameLabels = (ctx.contents.root->Belt_Option.getExn).frameLabels
    ctx.contents.frames->Belt_HashMapString.set(
        label,
        createFrame(
            ~ctx,
            ~ord=frameLabels->Js_array2.length,
            ~isAxiom, ~label, ~exprStr, ~proof,
            ~tokenType = if (proof->Belt_Option.isNone) {"an axiom"} else {"a theorem"},
            ()
        )
    )
    frameLabels->Js_array2.push(label)->ignore

    // adding additional assertions
    for i in 1 to 4 {
        let newLabel = label ++ "---" ++ i->Belt_Int.toString
        let frameLabels = (ctx.contents.root->Belt_Option.getExn).frameLabels
        ctx.contents.frames->Belt_HashMapString.set(
            newLabel,
            createFrame(
                ~ctx,
                ~ord=frameLabels->Js_array2.length,
                ~isAxiom, ~label=newLabel, ~exprStr, ~proof,
                ~tokenType = if (proof->Belt_Option.isNone) {"an axiom"} else {"a theorem"},
                ()
            )
        )
        frameLabels->Js_array2.push(newLabel)->ignore
    }
}
```

**Comment by expln** [comment]
Looks like the initial question is resolved. Closing this issue. Please feel free to re-open it if anything remained unresolved.
