### ISSUE TITLE
Allow people to easily preload an existing proof

### ISSUE THREAD

**Issue by david-a-wheeler** [expln/metamath-lamp#8]
I think it'd be helpful to allow people to easily preload an existing proof into the prover. Obviously that's not necessary to create a new proof, but there are useful reasons for it:

1. You're new to Metamath & want to see what an existing proof looks like in the tool.
1. You'd like to see the visualizations on an existing proof. The visualizations are really cool, esp. for those new to Metamath.
3. You might want to create a proof that's similar to an existing proof.

If there are already existing statements, there should be a dialogue like "This will erase and replace your existing work. Are you sure you want to do this (y/N)?"

**Comment by david-a-wheeler** [comment]
E.g., I'd love to tell the tool to load up "2p2e4"; it would then load up to (but not including) 2p2e4, then load the steps to prove 2p2e4.

I find that it's much easier to help people understand how to create proofs by loading up an existing proof, seeing what it looks like, then erasing the steps & seeing if you can re-create it. It's much easier to learn how to do something when there's an answer key of solved problems :-).

**Comment by expln** [comment]
I am going to implement this. Viewing existing proofs with visualizations will be possible in the embedded proof explorer which I am developing now in develop branch. It will look similar to this - https://expln.github.io/metamath/asrt/2p2e4.html 

I already implemented a "temporary mode" - when whatever you edit in the editor does nor override content in another instance of the editor. However, "temporary mode" doesn't store the editor's content to the local storage, so closing a browser (or any internal error) will erase the editor's content. That's why it is "temporary". It is already implemented in develop branch. Initially I implemented it for opening proofs from URLs. But I am going to use it for loading existing proofs too.

**Comment by david-a-wheeler** [comment]
Visualizations sound interesting!!

However, what I meant here is that you could take an existing proof in a database and load it in as an *editable* proof. There are reasons to do this:

* This is great for learning - you can load an existing proof, delete some statements, and try to re-prove it
* It's also great for trying to improve a proof, e.g., to make it shorter or remove use of an axiom.
* It also would make it easier to split a proof into smaller pieces (e.g., to pull out a lemma).

**Comment by david-a-wheeler** [comment]
Please do *NOT* use temporary mode when loading a proof ("Import from JSON"). Otherwise there's no easy way to store state for it to be easily reloaded later. "Import from JSON" is basically the only way to reload current state into a different browser. I routinely switch between my laptop and my phone, for example.

**Comment by expln** [comment]
I will not use TEMP mode when loading a proof. TEMP mode is used only when it is very easy to load a proof, for example, by clicking a link. Loading from JSON and loading an existing proof from the current context (this feature is to be implemented yet) is not so easy and users are expected to understand what they are doing, so no need in TEMP mode in these cases.

**Comment by expln** [comment]
Preloading an existing proof is available on dev https://expln.github.io/lamp/dev/index.html

In order to load an existing proof:
1. Open the Explorer tab and find a theorem.
2. Click the theorem name, so it opens in a new tab.
3. In that new tab, open the "hamburger" menu and select "Load this proof to the editor". This will open a dialog window.
4. The dialog window shows two parameters:
"Adjust the context" - If this parameter is checked then mm-lamp will change the context to include everything up to the theorem but not more. If this parameter is unchecked then the context will not be changed.
"Load proof steps" - If this parameter is checked then mm-lamp will load all the steps of the proof. If this parameter is unchecked then mm-lamp will not load proof steps; only hypothesis steps and the goal step will be loaded. This may be used to try to prove an existing theorem from the scratch for learning purposes.
5. Select/unselect these two parameters depending on your needs and click the "Load" button. The proof should be loaded to the editor tab.

**Comment by CatsAreFluffy** [comment]
If the proof contains multiple occurrences of the same statement (eg lines 1 and 3 of ~ sbth), after loading the proof to the editor there are errors from repeated lines. I'd expect repeated lines to be automatically merged, like in the metamath.org view.

**Comment by expln** [comment]
> If the proof contains multiple occurrences of the same statement (eg lines 1 and 3 of ~ sbth), after loading the proof to the editor there are errors from repeated lines. I'd expect repeated lines to be automatically merged, like in the metamath.org view.

This is ready on [dev ](https://expln.github.io/lamp/dev/index.html)

**Comment by expln** [comment]
This is available in [version 16](https://expln.github.io/lamp/v16/index.html)
